/* define colour codes as per theme */
#define YUKARI_BG 0x282c30FF
#define YUKARI_BASE0 0x1c2024FF
#define YUKARI_BASE5 0x5b6265FF
#define YUKARI_WHITE 0xf8f8f8FF

#define YUKARI_RED 0x931c12FF
#define YUKARI_DARKBLUE 0x9ba8beFF
#define YUKARI_MAGENTA 0xa24ed1FF


/* assign theme to elements */
#define TAG_BACK YUKARI_BASE0
#define TAG_HIGH YUKARI_MAGENTA
#define TAG_BORD YUKARI_BASE0
#define TAG_TEXT YUKARI_BASE5
#define TAG_HTEXT YUKARI_WHITE

#define BODY_BACK YUKARI_BG
#define BODY_HIGH YUKARI_MAGENTA
#define BODY_BORD YUKARI_BASE0
#define BODY_TEXT YUKARI_WHITE
#define BODY_HTEXT YUKARI_WHITE

#define BUTTON YUKARI_MAGENTA
#define LAYOUT_BOX YUKARI_RED

#define BUT_2 YUKARI_RED
#define BUT_3 YUKARI_DARKBLUE
