PLAN9=/usr/local/plan9 export PLAN9
PATH=$PATH:$PLAN9/bin export PATH
export acmeshell=/usr/local/plan9/bin/rc
PATH=$PATH:~/bin/acme export PATH
export acmeshell=/usr/local/plan9/bin/rc

## patch the cd command in bash to work well with `win`
if [ "$winid" ]; then
  ## ... then patch the `cd` command
  _cd () {
    \cd "$@" && awd
  }
  alias cd=_cd
fi

